{% set name = "mne-icalabel" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa62976d9c623df4913e74c7741904c509628dc5964540be8b16e691309f5701

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=46.4.0
    - wheel
  run:
    - python >=3.7
    - importlib-resources  # Normally only needed for py<39, but we're going noarch here!
    - importlib-metadata  # Normally only needed for py<38, but we're going noarch here!
    - mne-base >=1.0
    - numpy >=1.21
    - scipy >=1.2.0
    - pytorch
    - pooch
    - joblib  # ICA
    - scikit-learn  # ICA
    - python-picard  # ICA
    - qtpy  # GUI
    - mne-qt-browser  # GUI
    - matplotlib  # GUI

test:
  imports:
    - mne_icalabel
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://mne.tools/mne-icalabel/stable/
  summary: MNE-ICALabel is a Python package for labeling independent components that stem from an Independent Component Analysis (ICA).
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/mne-tools/mne-icalabel

extra:
  recipe-maintainers:
    - hoechenberger
    - larsoner
    - adam2392
    - mscheltienne
